#!/usr/bin/env python3
"""Layer 6 -- render a scaffold into a disposable tree, and receipt what happened.

This layer actually writes files. That is deliberate: the lease boundary is the
one control in this module that can be checked physically rather than asserted,
and a fixture claiming "writes outside the lease are refused" proves nothing
about the code that does the writing.

Two properties are enforced here rather than described:

1. every write is resolved and confirmed to land under the leased output root,
   including after symlink resolution -- a `../` in a target path or a symlink
   planted in the output tree both reach outside, and only one of them is
   visible in the plan;
2. the same plan rendered twice produces byte-identical trees. Nondeterminism is
   allowed only where the plan declares an entropy source, and then it is named
   in the receipt rather than smoothed over.

The receipt is CANDIDATE. Nothing in this module applies a scaffold, merges
anything, or promotes a state. The word appears once, at the end, and it is the
only verdict this module is entitled to reach.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from kc_common import (
    ContractError,
    digest,
    text_digest,
)

RECEIPT_SCHEMA = "loopx/knowledge-scaffold-receipt/v1"


def _resolve_within(root: Path, relative: str) -> Path:
    """Resolve a target path and prove it stays inside the leased root.

    `os.path.realpath` rather than a string prefix test: a symlink inside the
    output tree pointing at the developer's checkout satisfies every string
    check and still writes outside.
    """
    root_real = Path(os.path.realpath(root))
    candidate = Path(os.path.realpath(root / relative))
    if candidate != root_real and root_real not in candidate.parents:
        raise ContractError(
            f"scaffold target {relative!r} resolves to {candidate}, outside the leased "
            f"output tree {root_real}; a generated tree that can reach out of its "
            "lease can edit the checkout that asked for it"
        )
    return candidate


def render_body(op: dict[str, Any], spec_requirements: dict[str, Any]) -> str:
    """The generated file content. A pure function of the plan and the spec.

    Provenance is written into the file, not just the receipt: a symbol found in
    a diff six months later should carry its own citation, because that is the
    moment someone asks where the requirement came from.
    """
    lines = [
        '"""Candidate scaffold. Generated by the LoopX knowledge compiler.',
        "",
        "This file is a CANDIDATE. It has not been admitted, and no claim it",
        "encodes is verified by its own existence.",
        "",
        "Provenance:",
    ]
    for assertion_id in op["provenance"]["assertion_ids"]:
        lines.append(f"    assertion {assertion_id}")
    for locator in op["provenance"]["locators"]:
        lines.append(f"    source    {locator}")
    lines += ['"""', "", "from __future__ import annotations", ""]

    for requirement_id in op["requirement_ids"]:
        requirement = spec_requirements[requirement_id]
        lines.append("")
        lines.append(f"# {requirement_id}: {requirement['statement']}")
        for case in requirement["acceptance_cases"]:
            # One stub per acceptance case, so the compression the spec layer
            # refused cannot reappear as one function covering three cases.
            lines.append(
                f"# case {case['case_id']} (from {case['assertion_id']}): "
                f"given {case['given']}, expect {case['expect']}"
            )
    for symbol in op["expected_diff_shape"]["added_symbols"]:
        lines.append("")
        lines.append("")
        lines.append(f"def {symbol}() -> None:")
        lines.append(
            '    raise NotImplementedError("candidate scaffold; not admitted")'
        )
    return "\n".join(lines) + "\n"


def render(
    plan: dict[str, Any], spec: dict[str, Any], output_root: Path
) -> dict[str, Any]:
    """Write the scaffold. Returns what was written, never a verdict."""
    requirements = {r["requirement_id"]: r for r in spec["requirements"]}
    output_root.mkdir(parents=True, exist_ok=True)

    written = []
    for op in plan["operations"]:
        if op["intent"] != "CREATE":
            # Only CREATE is rendered in this leaf. UPDATE/DELETE/RENAME against
            # a real tree require the precondition to be evaluated against that
            # tree, which is a Human-Admit-gated application, not a compile.
            continue
        relative = op["target"]["path"]
        destination = _resolve_within(output_root, relative)
        if destination.exists():
            raise ContractError(
                f"{op['op_id']} has precondition PATH_ABSENT but {relative!r} already "
                "exists in the output tree"
            )
        destination.parent.mkdir(parents=True, exist_ok=True)
        body = render_body(op, requirements).encode("utf-8")
        destination.write_bytes(body)
        written.append(
            {"path": relative, "digest": text_digest(body), "bytes": len(body)}
        )
    return {
        "files": sorted(written, key=lambda entry: entry["path"]),
        "tree_digest": digest(sorted(written, key=lambda entry: entry["path"])),
    }


def declared_entropy(plan: dict[str, Any]) -> list[str]:
    """Entropy sources this plan admits to. Empty means the render must be exact."""
    sources = []
    for op in plan["operations"]:
        if op["target"]["selector_kind"] == "REGION" and "$RANDOM" in op["target"].get(
            "selector", ""
        ):
            sources.append(op["op_id"])
    return sorted(sources)


def emit_receipt(
    notes_subject: dict[str, Any],
    compiler_identity: str,
    plan: dict[str, Any],
    rendered: dict[str, Any],
    gates: list[dict[str, Any]],
    unresolved: dict[str, Any],
) -> dict[str, Any]:
    """The candidate receipt. Gaps are fields, not omissions."""
    for gate in gates:
        if gate["state"] not in {
            "PASS",
            "FAIL",
            "NOT_EXERCISED",
            "ABSENT",
            "SKIPPED_BY_POLICY",
        }:
            raise ContractError(
                f"gate {gate['name']!r} has unknown state {gate['state']!r}"
            )

    failed = sorted(g["name"] for g in gates if g["state"] != "PASS")
    return {
        "schema_version": RECEIPT_SCHEMA,
        "notes_subject": notes_subject,
        "compiler_identity": compiler_identity,
        "output_lease": plan["output_lease"],
        "scaffold": rendered,
        "gates": sorted(gates, key=lambda g: g["name"]),
        "unresolved": unresolved,
        "declared_entropy_sources": declared_entropy(plan),
        # The only verdict this module reaches. Applying it, merging it or
        # promoting it are Human Admit, and none of them happen here.
        "state": "CANDIDATE",
        "admit_required": True,
        "non_passing_gates": failed,
        "authority": "PROPOSES",
    }


def validate_receipt(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ContractError("scaffold receipt must be an object")
    if value.get("schema_version") != RECEIPT_SCHEMA:
        raise ContractError("scaffold receipt schema version drifted")
    if value.get("state") != "CANDIDATE":
        raise ContractError(
            f"scaffold receipt state is {value.get('state')!r}; this module emits "
            "CANDIDATE only, and any other state would be a promotion it has no "
            "authority to make"
        )
    if value.get("admit_required") is not True:
        raise ContractError("scaffold receipt must require Human Admit")
    unresolved = value.get("unresolved")
    if not isinstance(unresolved, dict) or set(unresolved) != {
        "open_unknowns",
        "open_contradictions",
        "uncovered_requirements",
    }:
        raise ContractError(
            "scaffold receipt.unresolved must name open unknowns, open "
            "contradictions and uncovered requirements; a receipt that omits its "
            "gaps reads as a receipt with none"
        )
    return value
