#!/usr/bin/env python3
"""Validate bettor-arena's runtime-env consumer binding without network access.

The default mode reads worktree files. ``--staged`` reads both artifacts from
Git's index, which is the pre-commit contract: judge exactly the bytes being
committed and never consult a sibling runtime-env checkout. Upstream freshness
is deliberately outside this gate and is checked explicitly with
``runtime-env sync --check``.

Exit codes: 0 valid · 2 missing/drifted/unsafe binding · 64 usage or Git failure.
Selftest: --selftest runs good and planted-bad controls without network access.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import tempfile
from typing import Any

from _gate_common import repo_root


BINDING_ID = "bettor-arena-local"
BINDING_REL = f".runtime-env/bindings/{BINDING_ID}.json"
EXAMPLE_REL = f".runtime-env/examples/{BINDING_ID}.env.example"
SOURCE_REPOSITORY = "https://github.com/ed3c/runtime-env"
HEX40 = re.compile(r"^[0-9a-f]{40}$")
HEX64 = re.compile(r"^[0-9a-f]{64}$")
VARIABLE_NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")


def _sha256(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _canonical_json(document: dict[str, Any]) -> str:
    return json.dumps(
        document, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )


def _read(root: Path, relative: str, staged: bool) -> str | None:
    if not staged:
        path = root / relative
        try:
            return path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return None
        except (OSError, UnicodeDecodeError) as exc:
            raise RuntimeError(f"cannot read {relative}: {exc}") from exc
    result = subprocess.run(
        ["git", "-C", str(root), "show", f":{relative}"],
        text=True,
        capture_output=True,
    )
    if result.returncode == 0:
        return result.stdout
    if "does not exist" in result.stderr or "exists on disk" in result.stderr:
        return None
    raise RuntimeError(f"cannot read staged {relative}: {result.stderr.strip()}")


def _render(variables: list[dict[str, Any]]) -> str:
    lines = ["# Generated by runtime-env. Values are placeholders, never credentials."]
    for variable in variables:
        requirement = "required" if variable["required"] else "optional"
        sensitivity = "secret" if variable["secret"] else "non-secret"
        lines.append(f"# {requirement}; {sensitivity}: {variable['description']}")
        lines.append(f"{variable['name']}={variable.get('default', '')}")
    return "\n".join(lines) + "\n"


def validate(binding_text: str | None, example_text: str | None) -> list[str]:
    failures: list[str] = []
    if binding_text is None:
        failures.append(f"missing {BINDING_REL}")
    if example_text is None:
        failures.append(f"missing {EXAMPLE_REL}")
    if failures:
        return failures

    try:
        document = json.loads(binding_text)
    except json.JSONDecodeError as exc:
        return [f"invalid JSON in {BINDING_REL}: {exc}"]
    if not isinstance(document, dict):
        return [f"{BINDING_REL} must contain an object"]

    expected_top = {
        "binding",
        "content_sha256",
        "profile",
        "render",
        "schema",
        "source",
        "variables",
    }
    if set(document) != expected_top:
        failures.append("binding top-level fields do not match consumer-binding/v1")
    if document.get("schema") != "runtime-env/consumer-binding/v1":
        failures.append("binding schema is not runtime-env/consumer-binding/v1")
    if document.get("binding") != BINDING_ID or document.get("profile") != BINDING_ID:
        failures.append(f"binding and profile must both be {BINDING_ID}")

    source = document.get("source")
    if not isinstance(source, dict) or set(source) != {"repository", "commit", "tree"}:
        failures.append("source must contain exactly repository, commit, and tree")
    else:
        if source.get("repository") != SOURCE_REPOSITORY:
            failures.append(f"source repository must be {SOURCE_REPOSITORY}")
        if not isinstance(source.get("commit"), str) or not HEX40.fullmatch(
            source["commit"]
        ):
            failures.append(
                "source commit must be a 40-character lowercase Git object ID"
            )
        if not isinstance(source.get("tree"), str) or not HEX40.fullmatch(
            source["tree"]
        ):
            failures.append(
                "source tree must be a 40-character lowercase Git object ID"
            )

    variables = document.get("variables")
    if not isinstance(variables, list) or not variables:
        failures.append("variables must be a non-empty array")
        variables = []
    seen: set[str] = set()
    allowed_variable = {
        "name",
        "required",
        "secret",
        "description",
        "account_url",
        "default",
    }
    required_variable = {"name", "required", "secret", "description"}
    for position, variable in enumerate(variables):
        label = f"variables[{position}]"
        if not isinstance(variable, dict):
            failures.append(f"{label} must be an object")
            continue
        if not required_variable.issubset(variable) or not set(variable).issubset(
            allowed_variable
        ):
            failures.append(f"{label} fields do not match the binding contract")
            continue
        name = variable.get("name")
        if not isinstance(name, str) or not VARIABLE_NAME.fullmatch(name):
            failures.append(f"{label}.name is invalid")
        elif name in seen:
            failures.append(f"duplicate variable {name}")
        else:
            seen.add(name)
        if not isinstance(variable.get("required"), bool):
            failures.append(f"{label}.required must be boolean")
        if not isinstance(variable.get("secret"), bool):
            failures.append(f"{label}.secret must be boolean")
        if (
            not isinstance(variable.get("description"), str)
            or not variable["description"].strip()
        ):
            failures.append(f"{label}.description must be non-empty")
        if variable.get("secret") is True and "default" in variable:
            failures.append(f"secret variable {name} must not have a default")
        if "default" in variable and not isinstance(variable["default"], str):
            failures.append(f"{label}.default must be a string")
        account_url = variable.get("account_url")
        if account_url is not None and (
            not isinstance(account_url, str) or not account_url.startswith("https://")
        ):
            failures.append(f"{label}.account_url must be HTTPS")
    names = [v.get("name") for v in variables if isinstance(v, dict)]
    if names != sorted(names):
        failures.append("variables must be sorted by name")

    render = document.get("render")
    if not isinstance(render, dict) or set(render) != {"format", "path", "sha256"}:
        failures.append("render must contain exactly format, path, and sha256")
    else:
        if render.get("format") != "dotenv" or render.get("path") != EXAMPLE_REL:
            failures.append("render must target the canonical bettor-arena dotenv path")
        if not isinstance(render.get("sha256"), str) or not HEX64.fullmatch(
            render["sha256"]
        ):
            failures.append("render sha256 must be lowercase hexadecimal")

    digest = document.get("content_sha256")
    unsigned = dict(document)
    unsigned.pop("content_sha256", None)
    if not isinstance(digest, str) or not HEX64.fullmatch(digest):
        failures.append("content_sha256 must be lowercase hexadecimal")
    elif digest != _sha256(_canonical_json(unsigned)):
        failures.append("binding content_sha256 does not match its content")

    if not failures:
        expected_example = _render(variables)
        if example_text != expected_example:
            failures.append("dotenv example does not match binding variables")
        if isinstance(render, dict) and render.get("sha256") != _sha256(
            expected_example
        ):
            failures.append("render sha256 does not match the deterministic projection")
    return failures


def run(root: Path, staged: bool) -> int:
    scope = "staged index" if staged else "worktree"
    print(f"check_runtime_env_binding: scanning {scope} {root}")
    try:
        failures = validate(
            _read(root, BINDING_REL, staged),
            _read(root, EXAMPLE_REL, staged),
        )
    except RuntimeError as exc:
        print(f"FATAL: {exc}", file=sys.stderr)
        return 64
    for failure in failures:
        print(f"RUNTIME-ENV-DRIFT {failure}", file=sys.stderr)
    if failures:
        return 2
    print("PASS: runtime-env binding and dotenv projection agree")
    return 0


def _fixture() -> tuple[str, str]:
    variables = [
        {
            "default": "http://localhost:11434",
            "description": "Ollama service root.",
            "name": "OLLAMA_URL",
            "required": False,
            "secret": False,
        }
    ]
    example = _render(variables)
    document: dict[str, Any] = {
        "binding": BINDING_ID,
        "profile": BINDING_ID,
        "render": {"format": "dotenv", "path": EXAMPLE_REL, "sha256": _sha256(example)},
        "schema": "runtime-env/consumer-binding/v1",
        "source": {
            "commit": "a" * 40,
            "repository": SOURCE_REPOSITORY,
            "tree": "b" * 40,
        },
        "variables": variables,
    }
    document["content_sha256"] = _sha256(_canonical_json(document))
    return json.dumps(document, indent=2, sort_keys=True) + "\n", example


def _selftest() -> int:
    good_binding, good_example = _fixture()
    tampered = json.loads(good_binding)
    tampered["profile"] = "other"
    secret_default = json.loads(good_binding)
    secret_default["variables"][0]["secret"] = True
    secret_default["content_sha256"] = _sha256(
        _canonical_json(
            {k: v for k, v in secret_default.items() if k != "content_sha256"}
        )
    )
    traversal = json.loads(good_binding)
    traversal["render"]["path"] = "../outside.env"
    traversal["content_sha256"] = _sha256(
        _canonical_json({k: v for k, v in traversal.items() if k != "content_sha256"})
    )
    cases = [
        ("good", good_binding, good_example, False),
        ("missing-binding", None, good_example, True),
        ("tampered-example", good_binding, good_example + "# drift\n", True),
        ("tampered-binding-digest", json.dumps(tampered), good_example, True),
        ("secret-default", json.dumps(secret_default), good_example, True),
        ("render-path-traversal", json.dumps(traversal), good_example, True),
    ]
    red = []
    for name, binding, example, should_fail in cases:
        failed = bool(validate(binding, example))
        if failed != should_fail:
            red.append(f"{name}: failed={failed}, want {should_fail}")
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        subprocess.run(["git", "-C", str(root), "init", "-q", "-b", "main"], check=True)
        for relative, content in (
            (BINDING_REL, good_binding),
            (EXAMPLE_REL, good_example),
        ):
            destination = root / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8")
        subprocess.run(["git", "-C", str(root), "add", "-A"], check=True)
        staged_good = run(root, staged=True)
        (root / EXAMPLE_REL).write_text(
            good_example + "# worktree drift\n", encoding="utf-8"
        )
        staged_ignores_worktree = run(root, staged=True)
        worktree_sees_drift = run(root, staged=False)
        for name, got, want in (
            ("staged-good", staged_good, 0),
            ("staged-ignores-worktree", staged_ignores_worktree, 0),
            ("worktree-sees-drift", worktree_sees_drift, 2),
        ):
            if got != want:
                red.append(f"{name}: got {got}, want {want}")
    for failure in red:
        print(f"SELFTEST case failed — {failure}", file=sys.stderr)
    print("SELFTEST " + ("GREEN" if not red else "RED"))
    return 0 if not red else 1


def main(argv: list[str]) -> int:
    if argv == ["--selftest"]:
        return _selftest()
    if argv not in ([], ["--staged"]):
        print(__doc__.strip(), file=sys.stderr)
        return 64
    root = repo_root(Path(__file__).resolve().parent)
    if root is None:
        print("check_runtime_env_binding: not inside a git work tree", file=sys.stderr)
        return 64
    return run(root, staged=argv == ["--staged"])


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
